### ISSUE TITLE
Mention application's own license in About

### ISSUE THREAD

**Issue by mikini** [froodyapp/froody-android#14]
In the application's About and the [About->Show licences](https://github.com/froodyapp/froody-android/blob/master/app/src/main/res/raw/licenses.html) dialogs I see only mention of the licenses of the used third party components (CC BY 4.0, MIT, Apache). Nowhere [the license for the application itself](https://github.com/froodyapp/froody-android/blob/master/LICENSE.md) (GNU GPL) is mentioned.

Sidenote: in [README.md](https://github.com/froodyapp/froody-android/blob/master/README.md) and [licenses.html](https://github.com/froodyapp/froody-android/blob/master/app/src/main/res/raw/licenses.html#L17) "CC-BY 4.0" is used to refer to a Creative Commons license. The standard and authoritative reference to CC licenses are with a space after CC; eg. ["CC BY 4.0"](https://creativecommons.org/licenses/by/4.0/). A dash is only added to group two or more attributes of the used CC license (like ["CC BY-NC-SA 4.0"](https://creativecommons.org/licenses/by-nc-sa/4.0/)).

**Comment by gsantner** [comment]
Thanks for pointing out!
The app's GPLv3 will get added to the About screen (not to dialog).

**Comment by gsantner** [comment]
![screenshot_20170319-142712](https://cloud.githubusercontent.com/assets/6735650/24081240/42e64960-0cb0-11e7-9065-4737c7cb2659.png)
