### ISSUE TITLE
Free and Voluntary donation types

### ISSUE THREAD

**Issue by slsimic** [froodyapp/froody-android#15]
#### General information
bringing the discussion from Crowdin
QUOTE gsantner
I thought it's easier for people to choose this way. I kept get asking by people whats the difference of "free" and "donation" and I always answered they are basically the same. Which is correct I would say, also both ways (voulantry AND free+donation) always imply that at least a "thank you" is needed, thats how everyone is thinking (if I take something I have to do something) - that imagination can't be eliminated by this app (or the decision), even if "Free" is an option
I really thought took some time to think about this all, and I would say thats a good solution.
We can of course discuss with others, but it would be better to do this on projects github issue page
***********************************
I would just repeat what I said at Crowdin... I think Free and Voluntary donation are not same and should be separated.
And "thank you" is not what is expected with Voluntary donation
but I think anyone with minimum decency and manners would "give" "Thank you!"
in both cases, whether he gets something for Free or by Voluntary donation :-)

**Comment by gsantner** [comment]
What do you think of "Unconditionally free"?

**Comment by slsimic** [comment]
I think there is really no need to complicate simple situation. :-)
What is the difference between Free and Unconditionally free? Because if it's unconditionally free you wouldn't expect simple "Thank you" ?
Well, if you take something for Free common courtesy and decency is to at least say "Thank you", isn't it.
And if someone does not have it, I don't think Free or Unconditionally free would make the difference.
Again, keep it simple, w/o introducing many unnecessary option.
1. Free - you give away stuff
2. (Voluntary) Donation - you give away but you expect some amount of money *even the smallest one
3. Selling - you put the price on your goods
4. Exchange - you expect offering some other goods in exchange

Maybe you can consider offering multiple choices, like check boxes.
For example, I would give something for free, but I don't mind if you make a donation or give me some of your goods you have.
Keep up the good work. ;-)

**Comment by gsantner** [comment]
Thanks for your input. We will keep Free as an option for now. I'm looking for a good icon, I couldn't find any good one yet. A striked out money symbol e.g. may deliver a "wrong"/" error" feeling, which I dont want it to do. Any suggestions? (Idea / Artwork)

**Comment by slsimic** [comment]
Tough one... When you search "icon free" you'll get all the free icons in the world.
Maybe some gift icon. But most of them are wrapped with bow tie. :-)
If you enter "picking" or "fruit picking" "cherry picking" in Google picture search, maybe you can get something interesting.
Or something like offering hands [http://www.freeimages.com/premium/hand-offer-save-icon-set-1509646](url)

**Comment by gsantner** [comment]
Yeah I also thought about the hands. I already added them as the donation option (https://github.com/froodyapp/froody-extras/blob/master/img/screens/v0.2.5/Screenshot_20170423-152521.png). I could go for a differnt one for donation and use that one at free, but I think the shaking hands are quite good for the donation option

**Comment by gsantner** [comment]
@slsimic  <https://openclipart.org/detail/193249/zero> maybe? Looks nice, is a zero and easy to remember

**Comment by slsimic** [comment]
Sorry but this ZERO is too ugly for me. :-)

**Comment by gsantner** [comment]
Now both, "Free" and "Not certified" used the "Okay"-Handsign
