### ISSUE TITLE
Russian language

### ISSUE THREAD

**Issue by guland2000** [froodyapp/froody-android#16]
Russian language is done 100%, please check it on https://crowdin.com/project/froodyapp hope i did not miss anything.
Will be great to see it on f-droid as soon as it possible.
Thank you for project!

**Comment by gsantner** [comment]
Thanks for translating! :+1: 
I approved most translation and commented otherwise

Is going to be included in next version

As noted: Translations have to match the source string.
E.g. a walnut is stilll a walnut, that doesn't depend on the area of living. It may vary a little, but e.g. walnut can't be translated with tomato. If something doesn't exist it can be added, but nothing should be translated differently just for reuse

**Comment by guland2000** [comment]
Maybe add: **Soy** - it can be _tofu, soy meat or beans_... For soy milk of course it will be just **Milk**...

**Comment by gsantner** [comment]
Sure.
Do you have any (vecor/svg) graphic available I could integrate for showing on map?

**Comment by guland2000** [comment]
I'm sorry, I do not quite understand what you mean. Graphic editor on the computer ?!

**Comment by gsantner** [comment]
I need an graphic that represents "soy milk" / "soy beans". So users can tap the icon on the map. For "soy milk" I think the normal milk one can be reused.

**Comment by guland2000** [comment]
You want to show me icon?!

**Comment by guland2000** [comment]
So for icons you can use from openclipart.org it is free even for commercial use.

**Comment by gsantner** [comment]
No, I asked if you got one I could use

**Comment by guland2000** [comment]
Aaaaa))) wait a minute

**Comment by guland2000** [comment]
Ex. soy bean https://openclipart.org/detail/20258/biofuel-concept
                     https://openclipart.org/detail/203224/soybean-beans
                     https://openclipart.org/detail/238309/soybean
For soy milk (_but we agreed to use the graph of ordinary **Milk**_) it сould be https://openclipart.org/detail/273350/soy-milk-carton
https://openclipart.org/detail/273220/soy-milk

**Comment by guland2000** [comment]
Tofu ))) https://openclipart.org/detail/210762/tofu-food

**Comment by gsantner** [comment]
Thanks for the suggestions!
If possible try to find a vector/svg image, so it scales good on all devices. One of them seems good, but the others seem to have too much drwaed stuff in the background

**Comment by guland2000** [comment]
Ok trying...

**Comment by guland2000** [comment]
Sutable for mobile app... as i see https://www.shutterstock.com/ru/image-vector/soybeans-food-allergy-green-vector-icon-262008179?i

**Comment by gsantner** [comment]
http://www.freepik.com/free-vector/food-elements-collection_1023941.htm#term=soybean&page=1&position=4

**Comment by guland2000** [comment]
Yeh i so it first... but dont like this words

> Free license with attribution

**Comment by gsantner** [comment]
If its e.g. Creative Commons its absolutely okay

**Comment by guland2000** [comment]
O! I did not inestige license uniside) If it is Ok why not!

**Comment by gsantner** [comment]
A breaker would be e.g. redistribution not allowed. or not allowed for commercial use.

**Comment by guland2000** [comment]
But i don not see graph just **Bean**(s)?! It can haricot bean(kidney bean) were to put it?

**Comment by gsantner** [comment]
Sorry, I don't quite understand

**Comment by guland2000** [comment]
graph Bean - do you have it ? Not soya... just beans black, red

**Comment by guland2000** [comment]
) Heintz in tomato souce...

**Comment by guland2000** [comment]
and herb not present here such youre lovely dandelion*,  Chamomile... Mint etc

**Comment by gsantner** [comment]
It's not getting better :D

You can always post links to images if you don't know the translation.
Are you talking about these: <https://duckduckgo.com/?q=kidney+bean&ia=images>

**Comment by guland2000** [comment]
Yes of course)))

**Comment by gsantner** [comment]
No, all images I got are now in the app already. For everything else I need to research and find a good matching image. I got many from here: <https://emojione.com/emoji/v3>

**Comment by guland2000** [comment]
Yes i so, but if you use openclipart.org it is for Absolutely for free, as far as I understood then the problems for the program ?! Technical I mean ...

**Comment by gsantner** [comment]
No its even better if it the source images are under public domain. But the openclipart.org images are mostly not vector graphics, which IMO are a lot better

**Comment by guland2000** [comment]
Yes but if you Download after pressing RED BUTTON it aways goes in SVG from openclipart....

**Comment by gsantner** [comment]
I think this doesn't work on all images, but really good if it does. Thought they only supply PNGs

**Comment by guland2000** [comment]
) i don not forget only RED BUTTON!!!

**Comment by gsantner** [comment]
so red on openclipart is always svg?

**Comment by guland2000** [comment]
In that case will be great to move all pictures to openclipart.They will be only glad) Even you will note them in youre app. Sure)

**Comment by guland2000** [comment]
Yes) Red!

**Comment by gsantner** [comment]
May be a good idea, yeah. Thank you for letting me know about oca svg.
From my point of view nothing speaks against this and everything can be migrated (excluding action icons, material icons)

Important for me is, that the images are good recognizeable. And if possible in a good quality (e.g. not black/white; drawing with faces inside and so on). I would also like to keep the style like it's currently, so no 3D-Icons (example for a cherry NOT wanted https://openclipart.org/detail/263389/cherries)

**Comment by guland2000** [comment]
Yeah agree with you 3D not usefull, but they have and 2D and an schematic just need to select... What better way what is not very good.

**Comment by gsantner** [comment]
@guland2000 Tell me if you got something.

**Comment by guland2000** [comment]
http://dryicons.com/free-icons/

**Comment by gsantner** [comment]
Soy bean is now added.
