### ISSUE TITLE
No free option of sharing

### ISSUE THREAD

**Issue by slsimic** [froodyapp/froody-android#17]
Whenever FREE way of sharing is choosen, app set DONATION instead
#### Steps to reproduce

1. …create what to share
2. …set way of distribution to FREE
3. … confirm everything

#### Expected result
**What is the expected output?** 
Icon placed on the map with FREE as way of distribution

**What do you see instead?**
Icon placed on the map with DONATION as way of distribution

One other thing...
When you adding or deleting items, FREE is correctly shown on both of the confirmation screens.

**Comment by gsantner** [comment]
Which version are you on?

**Comment by gsantner** [comment]
Got it, will be fixed in next version. <https://github.com/froodyapp/froody-android/blob/master/app/src/main/res/values/arrays.xml#L15>
It's just a display error, but it's correctly inserted in the database.

**Comment by slsimic** [comment]
0.2.6

**Comment by guland2000** [comment]
F-droid v2.0.4
What I'm doing wrong?!
Any updates in free open source repo?!

**Comment by gsantner** [comment]
F-Droid needs some time to build new versions. You can get the version which include the fix already from the Nightly repo, or from google play

**Comment by guland2000** [comment]
.... and will be great (just for FUN) will be great to see name translator in russian language:

> Андрей Гуляйкин: Russian translation

Why not...

**Comment by gsantner** [comment]
@guland2000 
I really appreciate your contributions, but please **don't** post to random issues where it doesn't belong to. Create new one if needed.

There is the center part missing, see CONTRIBUTORS.md file how the format is

**Comment by guland2000** [comment]
Not always now how to work with github interface, that is the reason, why i asked.
