### ISSUE TITLE
Pictures of products

### ISSUE THREAD

**Issue by guland2000** [froodyapp/froody-android#18]
The service will not be complete without the ability to add live photo products.
We live in a world where everyone wants to see what they want to get ... feel if you want.

**Comment by gsantner** [comment]
If you need more information ask.

Register on <https://hacktoberfest.digitalocean.com/>, send a PR to fix this and get your t-shirt for free :).

**Comment by djubreel** [comment]
Hello, I'd love to work on this, Can i get a little more information before I proceed? @gsantner

**Comment by gsantner** [comment]
yes, but I think it does not fit very well into hacktoberfest, this needs a very deep knowledge of the whole application suite. as it would need mofication/additions to API and the PHP server part too
