### ISSUE TITLE
Support connecting via a proxy

### ISSUE THREAD

**Issue by merge** [froodyapp/froody-android#19]
It'd be great to have the option to use Orbot to connect to the server safely, i.e. proxy settings in the app.

**Comment by gsantner** [comment]
Hi again! :D

In general, proxy may make sense.
While I usually support Tor as proxy in most of my apps and  the server allows it, I think in this case it's not an all too well idea. I think this will lead to the opposite, transmitting location data will deanonymize you if used with other services together over Tor.

Maybe it gets implemented later, somewhat like in dandelion:
![screenshot_20170524-140252](https://cloud.githubusercontent.com/assets/6735650/26402279/e66e151a-4089-11e7-83f2-fa9ce58df253.png)

**Comment by merge** [comment]
May very well be you're right but I don't get it :) How does location data deanoymize you and what do you mean by "used with other services together with Tor"?

I get location data via GPS and include that in my messages to your server. Why should I tell your sever what node I am connecting from, i.e. my IP address? And why should I tell my ISP that I am using froody? I may be totally mistaken, but shouldn't using Orbot fix that?

thanks

**Comment by gsantner** [comment]
>May very well be you're right but I don't get it :) How does location data deanoymize you and what do you mean by "used with other services together with Tor"?

I was talking about doing multiple activites at the same time may reveal more about the real identity:
* https://github.com/epidemics-scepticism/tor-misconception#use-it-consistently
* https://tor.stackexchange.com/a/13987
* https://www.whonix.org/wiki/Stream_Isolation

> I get location data via GPS and include that in my messages to your server. Why should I tell your sever what node I am connecting from, i.e. my IP address? And why should I tell my ISP that I am using froody? I may be totally mistaken, but shouldn't using Orbot fix that?

Thats the main part, which is a good point

**Comment by merge** [comment]
So Tor relays can do forensic analysis and work hard to try to de-anonymize somebody over long periods of time.

That's exactly what many Tor users want. Not actively reporting everything to your ISP, but instead requiring people to be a little busy when they want to know something about you. But isn't that a bit unrelated and ouside of froody's scope?

At least I don't yet see why having a proxy option would do harm. It would enable people to use Orbot without rooting the device. I kind of like froody (it needs users!) and at least for me it would be one step closer to being feature complete :)

**Comment by gsantner** [comment]
> At least I don't yet see why having a proxy option would do harm. It would enable people to use Orbot without rooting the device. 

I didn't say that at all, I would like to add it too, but it needs time. That is because the API gets autogenerated based on the API-specification (<https://github.com/froodyapp/froody-extras/blob/master/server/swagger.yaml>) which I would need to take a look at, what needs to bed manipulated to get proxy support (and this should/must also survive new API-client generations).

**Comment by gsantner** [comment]
@merge 
Got the app working with (any) proxy locally (tried with tor), at least the connection to the froody-server. 

For the connection to the Map-provider (OSM/MapNik) I found no way yet as the library seems to not support proxies. Maybe I'm missing something, but found no solution for that yet.

* <https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/tileprovider/tilesource/XYTileSource.java#L17>
* <https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/tileprovider/tilesource/TileSourceFactory.java>

![screenshot-2017-07-01__14-43-52](https://user-images.githubusercontent.com/6735650/27762133-c5c0e108-5e6b-11e7-95b9-497894c704f2.png)

**Comment by gsantner** [comment]
I reported the problem upstream and added proxy support to osmdroid. Made it into the latest release too.

**Comment by merge** [comment]
nice work. thanks for your support
