### ISSUE TITLE
website for database access

### ISSUE THREAD

**Issue by ramack** [froodyapp/froody-android#22]
Maybe I am thinking old-fashioned but I would prefer to have (also) an traditional website access to the database.
Also I think the project currently lacks publicity and I think with sharing links to content it would spread better, than if it is just accessible via app. - Think of facebook, blogs, etc. Also my parents, they are (meanwhile) familiar to the web, but they don't have a smartphone (yet) but a log of fruits...

**Comment by gsantner** [comment]
* Sharing: Just open a entry, theres the share button on the right. Redirects to homepage -> gplay if not installed
* Sharing: Theres also an recommend button in the "More" section of the app, which will create a short info and a link to the project
* Blog: <http://froody-app.at>
* Facebook: <https://www.facebook.com/froodyapp/?ref=br_rs>

Web-Client: Surely possible, but I don't have the manpower for it, but I would appreciate efforts by the community/contributors

**Comment by gsantner** [comment]
Under CC0 1.0 International  / public domain:
* Entry type images (food, cert, distri), in svg format
* Translations

This is a good base for to be included in a possible web client

**Comment by gsantner** [comment]
If you need more information ask.

Register on <https://hacktoberfest.digitalocean.com/>, send a PR to fix this and get your t-shirt for free :).
