### ISSUE TITLE
Allow messaging without external provider

### ISSUE THREAD

**Issue by ramack** [froodyapp/froody-android#23]
I would highly appreciate if I could create an account on the froody-server (best with a website access, see #22) and give only a rough location of the available fruits, while interested users could contact me via the froody system without the need to publish my contact data and garden location.

Maybe an XMPP server with a froody-account per user would be great to get in contact - I could easily integrate froody communication into my favorite chat app and be "available" whenever I am in the garden and have an easy was to stay in touch with someone interested in some fruits.

No problem sharing publicly a froody-account name of mine and the types and amount of fruits I can offer but mail address, garden location and phone number is not what I want to be visible to search engines.

**Comment by gsantner** [comment]
> I would highly appreciate if I could create an account on the froody-server (best with a website access, see #22) and give only a rough location of the available fruits, while interested users could contact me via the froody system without the need to publish my contact data and garden location.

You could do so by using the API, which is the app is using too. Heres the documenation: <https://github.com/froodyapp/froody-extras/blob/master/server/swagger.yaml>.

> Maybe an XMPP server with a froody-account per user would be great to get in contact - I could easily integrate froody communication into my favorite chat app and be "available" whenever I am in the garden and have an easy was to stay in touch with someone interested in some fruits.

Nice idea

> No problem sharing publicly a froody-account name of mine and the types and amount of fruits I can offer but mail address, garden location and phone number is not what I want to be visible to search engines.

Ehm, contact address and description is free-text. You can (and is intended for) enter tel/mail but you don't have to. The app and the server handles this as freetext.

> not what I want to be visible to search engines.

This is not and will not be indexed by search engines. They would first need to figure out how to get data, and the search-engine crawlers/google crawl websites, not contents coming from APIs of some application.

**Comment by ramack** [comment]
I must admit, that I did not use the app so far, just tried a bit. I do not really intend to do a own client for for the used protocol. The main idea was to have somehow a possibility __within__ the app to get in contact with someone who is interested in my fruits without giving further data - just a froody-user name...

For sure the main issue is usercount, that's also the reason why I suggested a web interface in #22 and I am willing to offer some fruits, but I was at home while checking the app and for me it looked, as the current GPS position is used for the location of the entry, which is not really what I would like, also not the garden, because I do not want users to just go there and take what is there.

**Comment by gsantner** [comment]
> The main idea was to have somehow a possibility within the app to get in contact with someone who is interested in my fruits without giving further data - just a froody-user name...

This was part of the first thoughts of the project and app - do it the complicated registration way - or another way. Because it was built from gound up to be as simple as possible to use - the decision was to not include registration and handle that automatically in the background, so the user can start right away. I hate it myself if I have to register at every page/project/game/service, whynot rely on technology thats already used and not to be reinvented. Thats why theres email and telephone suggested, but not mandatory, as everything can be entered. This decision is based on some other services/applications, how they realized this. The two ones using similar methods (not food but for general sharing/selling stuff) near me are pretty successful with this way. 

> For sure the main issue is usercount, that's also the reason why I suggested a web interface in #22 and I am willing to offer some fruits

Feel free to start contributing :)

> , but I was at home while checking the app and for me it looked, as the current GPS position is used for the location of the entry, which is not really what I would like, also not the garden, because I do not want users to just go there and take what is there.

Yes, current Position, or the last saved position is used. E.g. if you entered an entry, turn off locations, go to work you can still enter with the old position. Including a seperate map where one could choose was already suggested by someone, but I don't know yet in which way to include that in the app. I'm always giving the app some friends (young and old) to find out how they recognize what they have to do. Just including a map may make it more difficult.

**Comment by gsantner** [comment]
I'm closing this in favour of issue no 4. Everything other than position can be entered by hand and without any registration.

**Comment by ramack** [comment]
No problem to close this issue, but I am not sure whether you really got my point...
Somehow there are two types of anonymity: Anonymous for the froody-server and anonymous for other users. Both have reasonable points, but for me the second form seems more important, and for that a "froody-user-account" might be beneficial, if you would allow "in-froody-messages", as I would not be required to publish some form of contact information. At the moment, I would have to register a new email-address with some free mail hoster to put it into the contact field in froody, to stay really anonymous - which I consider far from being simple and user friendly.

The idea to not require an explicit registration is still a very good one, but maybe froody can support both:
- auto-register an account as currently
- provide the possibility to choose a username and password (in combination with registering an email address - with the usual test mail to validate it)
- mail notification (s discussed in #24) and profile attachment as in #5 and unlimited availability of the offers (with always the possibility to delete it, even after uninstall/install cycle of the app) can be allowed only if the profile is in a state where the user can "reconnect" to it

**Comment by gsantner** [comment]
in such cases I would prefer being able to use without email (as said as additional option to current solution)

**Comment by ramack** [comment]
for sure: allowing without email is perfectly fine! The only problem I see without email is, that the users might have a profile and cannot reconnect to it after loosing app settings or the password for a login. But this is also not a big problem, if the server cares about it.

e. g. unlimited offers I see problematic, because we should never have out-of date entries without an "interactionless" (by server admins) way to get rid of them. But maybe the profile (or the active offers connected to it) can also be automatically disabled if the profile is not used for more than 60 days. (app uninstalled / no login etc.)

**Comment by gsantner** [comment]
what i posted on other thread was just a suggestion, for beginning, not the final idea. The unlimited was about e.g. trees. Maybe 2 years is already like "unlimited". Admin: I always can delete entries and users.

**Comment by gsantner** [comment]
BTW: Are you developing for Android, or want to start? If you are interested in improving anything (Server: PHP, App: Java) feel free to start contributing. I can also give mentoring so you get the whole picture of the project.

**Comment by ramack** [comment]
So far I did not do anything for Android and I am not sure how much time I am willing to invest... and there are different apps which are attractive, so no clear yes or no from me. Sorry. We will See. And thanks for your offer to support me.

**Comment by gsantner** [comment]
If you need more information ask.

Register on <https://hacktoberfest.digitalocean.com/>, send a PR to fix this and get your t-shirt for free :).
