### ISSUE TITLE
notifications

### ISSUE THREAD

**Issue by ramack** [froodyapp/froody-android#24]
Do you see a chance to add some kind of notification feature? Such that I get notified in case someone adds an entry close to where I live? Maybe we some configurable radius?

I guess, that many people try froody but as soon as they see, that there are not many entries they get distracted. Maybe they keep the app installed for some time, but surely nobody will poll it. So with the app sending notifications for new entries might get users back...

And this is just too cool for never reaching the critical mass.

**Comment by gsantner** [comment]
Its absolutely something that would be nice to have yes. But we have to keep in mind that the majority of Froody users currently are F-Droid users, and so Google Play Notifications are not an option. This means the app has to poll the server itself from time time to time.

Step 1 would be to add the ability to set a "home location", which will then get a special treatment.

Step 2 a service which can poll in background at home location, and merge into the local entrybase. If the app is currently visible and polling service also running then thread safety must be unsured (think it currently is, but it needs a look into it anyway).

Step 3 is sending a notification to local device if service encountered new entries nearly

For this all the new Android O background lmitations must be considered.

I currently work on this, but any help is appreciated

**Comment by ramack** [comment]
great! I also think the app should definitely stay Google-free, but one more idea comes to my mind: which would be to use an email, sent by the server as soon as something new created in the radius. For sure, it requires registering with the email address, but if you would allow a configuration "send email notification" on update and require only then the email address it still is simple for the first setup. - And such kind of user profile on the server would also allow anonymous contact :-) see #23 

The effort on the server side would be probably higher in case you implement somehow a server side handling of the notification, but as it would reduce the load for the polling it might still be worth the effort.

**Comment by gsantner** [comment]
> update and require only then the email address it still is simple for the first setup. - And such kind of user profile on the server would also allow anonymous contact :-)

As said, it is already anonymous contact, one can enter whatever he wants as contact detail (be it telephone, email or whatever)

Sending emails shouldn't be the problem. But I think polling shouldn't be a too much problem either, because somewhat like once or twice per day should be very enough, which won't take much battery

**Comment by gsantner** [comment]
If you need more information ask.

Register on <https://hacktoberfest.digitalocean.com/>, send a PR to fix this and get your t-shirt for free :).
