### ISSUE TITLE
Allow to choose a location on the map other than current gps

### ISSUE THREAD

**Issue by Bugsbane** [froodyapp/froody-android#4]
I know where many local fruit trees have fruit accessible in public places around my area, however I really don't want to have to walk/drive to each one, just to be able to add them to this database. How about having the location default to where the map is centered, rather than the GPS location and/or letting people long click on the map to add am entry at that location?

**Comment by gsantner** [comment]
The thing is, you can't offer other people something you don't own. I understand that this maybe makes sense in such cases, but mostly the things to be shared will be at home, in the people's garden.
And for the `don't want to walk around`: See this as a advantage, it also keeps you healthy and active :D.

Maybe this gets added later, but currently it's not planned.

**Comment by Bugsbane** [comment]
> The thing is, you can't offer other people something you don't own.

I know if many fruit trees dropping fruit on the ground on public land, for example, the public park near my library has two apple trees, right next to a walking trail. They literally drop edible apples on a public walking trail. In an adjacent park, there are raspberry bushes that grow onto the sidewalk, bearing fruit. Is Froodly really better off without these?

> it also keeps you healthy and active :D.

I walk 8 hours a day for my job and play Pokemon Go, so I'm no stranger to walking. I just don't have time to physically go to reach location that I've ever found legally publically accessible food, and I'm sure many people are in the same situation. 

The usefulness of an app like Froody, lives or dies by the network effect, ie, the more people who use it, the more other people will be attracted to use it, either causing an exponential growth, completeness of data and usefulness, or virtually no growth / usefulness at all.

Limiting this to only the very small number of people who find the app, and have all of the available food they know of, growing in their back yard, is definitely not helping Froody to gain any kind of traction.

I understand that programming resources are likely very limited. I would just think very hard about embracing this limitation of the app as any kind of feature, rather than a challenge to hopefully be solved eventually (possibly with the help of other contributors).

**Comment by gsantner** [comment]
I'm open for pull requests, and if it gets done, it must be easy and understandable to use for everybody, maybe as additional option, but I would say - per default keep it using the available location.

**Comment by guland2000** [comment]
Ok, thank you for a great app.
I need to limit search (to see only one country on the map...).
One country, or maybe few, around border.
Is it possible to limit  this by request? From you?!

**Comment by guland2000** [comment]
So other then my country must be crossed out... and should not be available for making changes. So it is easier and more opportunities.

**Comment by gsantner** [comment]
Please create an own issue. This is not related.

I cannot see a reason to do this (crossing out others). You can always zoom out and at some point you will see your country and the countries borders.
We don't manage a list of countries and coordinates that are inside, neither server side nor client side. These informations do come from reverse geocoder.

**Comment by guland2000** [comment]
Ok! Agree with you.

**Comment by gsantner** [comment]
Removed comments unrelated to this issue

**Comment by gsantner** [comment]
If you need more information ask.

Register on <https://hacktoberfest.digitalocean.com/>, send a PR to fix this and get your t-shirt for free :).
