### ISSUE TITLE
More options for time range

### ISSUE THREAD

**Issue by Bugsbane** [froodyapp/froody-android#5]
While I know where many local food plants drop free food, none of them are doing so right now, so having entries be available for just three weeks means that I'm just not likely to add any entries. If I don't remember to come back to the app later, then these sources will likely never make it to the database, and I severely doubt I would be the only one in this boat.

How about letting people optionally put in a date range for approximately when that Froodly is available each year? You could still have it default to three weeks, but this would let users contribute in a way that could add laying value, even if the user only uses the app for a week. Ironically though, by having more entries available on the map, you actually make it more useful and encourage people to keep contributing themselves, for longer.

If you're limiting the app to only showing entries from the last three weeks, then you're severely limiting the network effect that this app needs to be useful.

**Comment by gsantner** [comment]
I understand, but how this can be managed? Just think of you inserting something, and your phone dies. You can't delete them in such cases anymore.
Also, should you be able to see those (inactive) entries on the map? My Entries section?

The main reason behind this whole 3 weeks limit is simple, most things that grow are just available in a limited time slot - because nature. This fact allows to save a lot of bandwidth, cache size on client, and database size on server.

**Comment by gsantner** [comment]
The limit was upped 60 days some versions ago. A more higher value seems to be a good idea, yes.

What about:
* Default 1 year, other options include 60 days, half year, 2 years, 5 years, unlimited
* Making profile exportable: That means the user can export the needed codes so he can delete the entries at a later point, even if he once uninstalled the app. 
* Import profile: Choose the backup file, which makes the user able to get access again

**Comment by ramack** [comment]
Mh. somehow the 60 days are not so bad I'd say, but it highly depends on what you offer (most fresh, naturally grown fruits are not seasoned longer than 60 days). But maybe I can offer the same fruits every year, so several years would also be somehow good.

Exporting and importing profile seems a good idea, but isn't this too complicated for most users? - Maybe you don't wanna hear that, but I personally would think that it is simpler to "register" with an email address and/or user name and password to be able to "reconnect" a new profile to the same - existing one. Also I have two android devices where I might use froody, so it would be good to use the same profile on both of them. -> Potentially even for the devices of my wife an me it would be good to share the same profile... (If you don't like that it is fine for me, still _I_ think it would be good)

**Comment by ramack** [comment]
unlimited is in my eyes not good, in case you cannot get into the same profile after loosing everything...

**Comment by gsantner** [comment]
If you need more information ask.

Register on <https://hacktoberfest.digitalocean.com/>, send a PR to fix this and get your t-shirt for free :).
