### ISSUE TITLE
Foodsharing?

### ISSUE THREAD

**Issue by rugk** [froodyapp/froody-android#6]
Would not it be more useful to integrate (it) into existing well-run projects such as [FoodSharing](https://foodsharing.de/), where everyone can share food, there are multiple clients and it already has a network.

I think it is bad for creating a big network (which is required to make this app useful) when you bind such a project to specific app and even more bad when you bind it to a specific type of food (aka fruits).
It would be more useful to support the already existing infrastructure/project IMHO.

**Comment by gsantner** [comment]
> well-run projects such as FoodSharing

FoodSharing seems to be a project mainly covering germany. They don't have an public available API, and the server part is non free. This is a project free as in freedom, and developed in public.

> when you bind such a project to specific app 

It's not bound to a specific app. The API (+documentation) is available. Everyone can build an app/service/page/whatever using that API.
