### ISSUE TITLE
Request: new distribution type "Swap"

### ISSUE THREAD

**Issue by Chewie9999** [froodyapp/froody-android#8]
I think it would be good to include a "swap" choice, so you can offer one type of produce in return for something different, instead of sale or donation.

**Comment by gsantner** [comment]
Hey, thanks for your request. Good idea!
Do you think "donation" is even needed?
So free, sell, swap - or free, donation, sell, swap?

**Comment by Chewie9999** [comment]
You're welcome :)
I've put our apples on, but I'm not seeing anyone else in the UK at the moment - is this expected (ie, no users yet)?
Not sure, some people may like "donation", I think there's no harm in leaving it.

**Comment by gsantner** [comment]
Yeah, right, because not much entries there yet (well it's winter ;) ). Entries are loaded of a 25km^2 area centered around your current map zommed location.

edit: maybe you can find one in glasgow city ;)

**Comment by Chewie9999** [comment]
@gsantner aah ok. I think i found you - "Miscellaneous" ? ;)
Fruit keeps a long time once harvested :) We've got shedloads of apples still!
In that case, it would be good to mention that in "About" or have some kind of overlay showing the current area that is loaded (at least until critical mass has been acheived!).

**Comment by gsantner** [comment]
Well, as the project description says, it's for use in the **local area**. If you need to drive e.g. 200 km just to get apple's, than this is absolutly not what this project is created for and shouldn't be used for.

**Comment by Chewie9999** [comment]
Very true, but some people's local is different to others!

**Comment by gsantner** [comment]
A option "Swap" or with the meaning of Swap will be included in the next version.

**Comment by gsantner** [comment]
@Chewie9999 Implemented and live.

**Comment by Chewie9999** [comment]
Thank you, already installed :)
