### ISSUE TITLE
Advertising: leaflet/business card for "side of the road" sellers

### ISSUE THREAD

**Issue by Chewie9999** [froodyapp/froody-android#9]
Some people in the UK sell things like eggs etc at the side of the road, usually at the end of the driveways to their houses etc. with a hand-written sign to accompany it.
I would think that these people might use your program, and I suggest a small printable advert for your app that I (and others) could drop off at these places so they can learn about your service.
Nothing fancy, but your logo, URL, QRCode for URL, and brief description of your service.
What do you think?
I could have a go at doing one as an SVG if you like?

**Comment by gsantner** [comment]
(I'm now just talking about QR-code, everything else (URL,Picture..) in inherited.)
What should the QR-code refer to? One entry? A location on the map? All by a user?

Note that `All by user` is not possible, because server removes this details when returning entries. This is a part of the security feature of the system.

**Comment by Chewie9999** [comment]
Sorry, I meant a QRcode to a link to install your App

**Comment by gsantner** [comment]
@Chewie9999 This is actually implemented! If you share an entry this always includes a link in this format <https://froodyapp.github.io/share.html?entryId=134> .
If you got the app installed, the entry gets displayed. if not, the webpage gets loaded.

**Comment by Chewie9999** [comment]
No, i mean as a hard copy to advertise your app to people that don't use it yet!

**Comment by gsantner** [comment]
Okay, now it's more clear for me. It's about advertising the app. Not about advertising a user or entry of the app.

SVG: Good suggestion! Maybe it's would also be great to have a new/different project icon (the current one is a icon of EmojiONE set)

**Comment by Chewie9999** [comment]
Exactly.
Fair enough.

**Comment by gsantner** [comment]
@Chewie9999  I'm currently busy with completing the semester, and can't programm or create stuff. Thank you for your interest! Note that everything that is meant to be used / or included in the repos - must be published in a libre license. Especially in such a case, the artwork/icon/banner must be allowed to use anywhere, without a backlink to e.g. homepage of a designer. (But possibly/optionally e.g. to the froody project).

By the way, there is the about section in the app, and the contributors file on GitHub where contributors get added. Thats where e.g. also people designing stuff will get listed.
